[build-system]
requires = ["maturin>=1.9.3,<2.0"]
build-backend = "maturin"

[project]
name = "amdb"
description = "AMDB - packaged Rust binary exposed as a Python package"
readme = "README.md"
requires-python = ">=3.8"
dynamic = ["version"]

[tool.maturin]
bindings = "bin"
manifest-path = "Cargo.toml"
module-name = "amdb"
python-source = "python"
strip = true
