name: Build binaries (amdb)

on:
  workflow_dispatch: {}

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Build wheels (maturin)
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: 'v1.11.5'
          command: build
          args: --release --locked --out dist --compatibility pypi

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist
